// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteProfileHandlerFunc turns a function with the right signature into a delete profile handler
type DeleteProfileHandlerFunc func(DeleteProfileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteProfileHandlerFunc) Handle(params DeleteProfileParams) middleware.Responder {
	return fn(params)
}

// DeleteProfileHandler interface for that can handle valid delete profile params
type DeleteProfileHandler interface {
	Handle(DeleteProfileParams) middleware.Responder
}

// NewDeleteProfile creates a new http.Handler for the delete profile operation
func NewDeleteProfile(ctx *middleware.Context, handler DeleteProfileHandler) *DeleteProfile {
	return &DeleteProfile{Context: ctx, Handler: handler}
}

/*DeleteProfile swagger:route DELETE /profile/{id} Preferences deleteProfile

Deletes a profile

*/
type DeleteProfile struct {
	Context *middleware.Context
	Handler DeleteProfileHandler
}

func (o *DeleteProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteProfileParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
