// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteOwnerHandlerFunc turns a function with the right signature into a delete owner handler
type DeleteOwnerHandlerFunc func(DeleteOwnerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteOwnerHandlerFunc) Handle(params DeleteOwnerParams) middleware.Responder {
	return fn(params)
}

// DeleteOwnerHandler interface for that can handle valid delete owner params
type DeleteOwnerHandler interface {
	Handle(DeleteOwnerParams) middleware.Responder
}

// NewDeleteOwner creates a new http.Handler for the delete owner operation
func NewDeleteOwner(ctx *middleware.Context, handler DeleteOwnerHandler) *DeleteOwner {
	return &DeleteOwner{Context: ctx, Handler: handler}
}

/*DeleteOwner swagger:route DELETE /owner/{id} Preferences deleteOwner

Deletes an Owner

*/
type DeleteOwner struct {
	Context *middleware.Context
	Handler DeleteOwnerHandler
}

func (o *DeleteOwner) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteOwnerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
