// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOwnerHandlerFunc turns a function with the right signature into a get owner handler
type GetOwnerHandlerFunc func(GetOwnerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOwnerHandlerFunc) Handle(params GetOwnerParams) middleware.Responder {
	return fn(params)
}

// GetOwnerHandler interface for that can handle valid get owner params
type GetOwnerHandler interface {
	Handle(GetOwnerParams) middleware.Responder
}

// NewGetOwner creates a new http.Handler for the get owner operation
func NewGetOwner(ctx *middleware.Context, handler GetOwnerHandler) *GetOwner {
	return &GetOwner{Context: ctx, Handler: handler}
}

/*GetOwner swagger:route GET /owner/{id} Preferences getOwner

Find Preference Owner by Id

Returns a single owner

*/
type GetOwner struct {
	Context *middleware.Context
	Handler GetOwnerHandler
}

func (o *GetOwner) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOwnerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
