// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"models"
)

// GetOwnerOKCode is the HTTP code returned for type GetOwnerOK
const GetOwnerOKCode int = 200

/*GetOwnerOK successful operation

swagger:response getOwnerOK
*/
type GetOwnerOK struct {

	/*
	  In: Body
	*/
	Payload *models.PreferenceOwner `json:"body,omitempty"`
}

// NewGetOwnerOK creates GetOwnerOK with default headers values
func NewGetOwnerOK() *GetOwnerOK {
	return &GetOwnerOK{}
}

// WithPayload adds the payload to the get owner o k response
func (o *GetOwnerOK) WithPayload(payload *models.PreferenceOwner) *GetOwnerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get owner o k response
func (o *GetOwnerOK) SetPayload(payload *models.PreferenceOwner) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOwnerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOwnerBadRequestCode is the HTTP code returned for type GetOwnerBadRequest
const GetOwnerBadRequestCode int = 400

/*GetOwnerBadRequest Invalid ID supplied

swagger:response getOwnerBadRequest
*/
type GetOwnerBadRequest struct {
}

// NewGetOwnerBadRequest creates GetOwnerBadRequest with default headers values
func NewGetOwnerBadRequest() *GetOwnerBadRequest {
	return &GetOwnerBadRequest{}
}

// WriteResponse to the client
func (o *GetOwnerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetOwnerNotFoundCode is the HTTP code returned for type GetOwnerNotFound
const GetOwnerNotFoundCode int = 404

/*GetOwnerNotFound Not found

swagger:response getOwnerNotFound
*/
type GetOwnerNotFound struct {
}

// NewGetOwnerNotFound creates GetOwnerNotFound with default headers values
func NewGetOwnerNotFound() *GetOwnerNotFound {
	return &GetOwnerNotFound{}
}

// WriteResponse to the client
func (o *GetOwnerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetOwnerInternalServerErrorCode is the HTTP code returned for type GetOwnerInternalServerError
const GetOwnerInternalServerErrorCode int = 500

/*GetOwnerInternalServerError Internal Error

swagger:response getOwnerInternalServerError
*/
type GetOwnerInternalServerError struct {
}

// NewGetOwnerInternalServerError creates GetOwnerInternalServerError with default headers values
func NewGetOwnerInternalServerError() *GetOwnerInternalServerError {
	return &GetOwnerInternalServerError{}
}

// WriteResponse to the client
func (o *GetOwnerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
