// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateOwnerOKCode is the HTTP code returned for type UpdateOwnerOK
const UpdateOwnerOKCode int = 200

/*UpdateOwnerOK success

swagger:response updateOwnerOK
*/
type UpdateOwnerOK struct {
}

// NewUpdateOwnerOK creates UpdateOwnerOK with default headers values
func NewUpdateOwnerOK() *UpdateOwnerOK {
	return &UpdateOwnerOK{}
}

// WriteResponse to the client
func (o *UpdateOwnerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateOwnerBadRequestCode is the HTTP code returned for type UpdateOwnerBadRequest
const UpdateOwnerBadRequestCode int = 400

/*UpdateOwnerBadRequest Invalid ID supplied

swagger:response updateOwnerBadRequest
*/
type UpdateOwnerBadRequest struct {
}

// NewUpdateOwnerBadRequest creates UpdateOwnerBadRequest with default headers values
func NewUpdateOwnerBadRequest() *UpdateOwnerBadRequest {
	return &UpdateOwnerBadRequest{}
}

// WriteResponse to the client
func (o *UpdateOwnerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateOwnerNotFoundCode is the HTTP code returned for type UpdateOwnerNotFound
const UpdateOwnerNotFoundCode int = 404

/*UpdateOwnerNotFound Definition not found

swagger:response updateOwnerNotFound
*/
type UpdateOwnerNotFound struct {
}

// NewUpdateOwnerNotFound creates UpdateOwnerNotFound with default headers values
func NewUpdateOwnerNotFound() *UpdateOwnerNotFound {
	return &UpdateOwnerNotFound{}
}

// WriteResponse to the client
func (o *UpdateOwnerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateOwnerMethodNotAllowedCode is the HTTP code returned for type UpdateOwnerMethodNotAllowed
const UpdateOwnerMethodNotAllowedCode int = 405

/*UpdateOwnerMethodNotAllowed Validation exception

swagger:response updateOwnerMethodNotAllowed
*/
type UpdateOwnerMethodNotAllowed struct {
}

// NewUpdateOwnerMethodNotAllowed creates UpdateOwnerMethodNotAllowed with default headers values
func NewUpdateOwnerMethodNotAllowed() *UpdateOwnerMethodNotAllowed {
	return &UpdateOwnerMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateOwnerMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// UpdateOwnerInternalServerErrorCode is the HTTP code returned for type UpdateOwnerInternalServerError
const UpdateOwnerInternalServerErrorCode int = 500

/*UpdateOwnerInternalServerError Internal Error

swagger:response updateOwnerInternalServerError
*/
type UpdateOwnerInternalServerError struct {
}

// NewUpdateOwnerInternalServerError creates UpdateOwnerInternalServerError with default headers values
func NewUpdateOwnerInternalServerError() *UpdateOwnerInternalServerError {
	return &UpdateOwnerInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateOwnerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
