// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateProfileOKCode is the HTTP code returned for type UpdateProfileOK
const UpdateProfileOKCode int = 200

/*UpdateProfileOK success

swagger:response updateProfileOK
*/
type UpdateProfileOK struct {
}

// NewUpdateProfileOK creates UpdateProfileOK with default headers values
func NewUpdateProfileOK() *UpdateProfileOK {
	return &UpdateProfileOK{}
}

// WriteResponse to the client
func (o *UpdateProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateProfileBadRequestCode is the HTTP code returned for type UpdateProfileBadRequest
const UpdateProfileBadRequestCode int = 400

/*UpdateProfileBadRequest Invalid ID supplied

swagger:response updateProfileBadRequest
*/
type UpdateProfileBadRequest struct {
}

// NewUpdateProfileBadRequest creates UpdateProfileBadRequest with default headers values
func NewUpdateProfileBadRequest() *UpdateProfileBadRequest {
	return &UpdateProfileBadRequest{}
}

// WriteResponse to the client
func (o *UpdateProfileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateProfileNotFoundCode is the HTTP code returned for type UpdateProfileNotFound
const UpdateProfileNotFoundCode int = 404

/*UpdateProfileNotFound Definition not found

swagger:response updateProfileNotFound
*/
type UpdateProfileNotFound struct {
}

// NewUpdateProfileNotFound creates UpdateProfileNotFound with default headers values
func NewUpdateProfileNotFound() *UpdateProfileNotFound {
	return &UpdateProfileNotFound{}
}

// WriteResponse to the client
func (o *UpdateProfileNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateProfileMethodNotAllowedCode is the HTTP code returned for type UpdateProfileMethodNotAllowed
const UpdateProfileMethodNotAllowedCode int = 405

/*UpdateProfileMethodNotAllowed Validation exception

swagger:response updateProfileMethodNotAllowed
*/
type UpdateProfileMethodNotAllowed struct {
}

// NewUpdateProfileMethodNotAllowed creates UpdateProfileMethodNotAllowed with default headers values
func NewUpdateProfileMethodNotAllowed() *UpdateProfileMethodNotAllowed {
	return &UpdateProfileMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateProfileMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// UpdateProfileInternalServerErrorCode is the HTTP code returned for type UpdateProfileInternalServerError
const UpdateProfileInternalServerErrorCode int = 500

/*UpdateProfileInternalServerError Internal Error

swagger:response updateProfileInternalServerError
*/
type UpdateProfileInternalServerError struct {
}

// NewUpdateProfileInternalServerError creates UpdateProfileInternalServerError with default headers values
func NewUpdateProfileInternalServerError() *UpdateProfileInternalServerError {
	return &UpdateProfileInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateProfileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
