// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"models"
)

// NewAddCategoryParams creates a new AddCategoryParams object
// with the default values initialized.
func NewAddCategoryParams() AddCategoryParams {
	var ()
	return AddCategoryParams{}
}

// AddCategoryParams contains all the bound params for the add category operation
// typically these are obtained from a http.Request
//
// swagger:parameters addCategory
type AddCategoryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Category that needs to be added
	  Required: true
	  In: body
	*/
	Category *models.Category
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddCategoryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Category
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("category", "body"))
			} else {
				res = append(res, errors.NewParseError("category", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Category = &body
			}
		}

	} else {
		res = append(res, errors.Required("category", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
