// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"models"
)

// AddDefinitionOKCode is the HTTP code returned for type AddDefinitionOK
const AddDefinitionOKCode int = 200

/*AddDefinitionOK Success

swagger:response addDefinitionOK
*/
type AddDefinitionOK struct {

	/*
	  In: Body
	*/
	Payload *models.PreferenceDefinition `json:"body,omitempty"`
}

// NewAddDefinitionOK creates AddDefinitionOK with default headers values
func NewAddDefinitionOK() *AddDefinitionOK {
	return &AddDefinitionOK{}
}

// WithPayload adds the payload to the add definition o k response
func (o *AddDefinitionOK) WithPayload(payload *models.PreferenceDefinition) *AddDefinitionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add definition o k response
func (o *AddDefinitionOK) SetPayload(payload *models.PreferenceDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddDefinitionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddDefinitionMethodNotAllowedCode is the HTTP code returned for type AddDefinitionMethodNotAllowed
const AddDefinitionMethodNotAllowedCode int = 405

/*AddDefinitionMethodNotAllowed Invalid input

swagger:response addDefinitionMethodNotAllowed
*/
type AddDefinitionMethodNotAllowed struct {
}

// NewAddDefinitionMethodNotAllowed creates AddDefinitionMethodNotAllowed with default headers values
func NewAddDefinitionMethodNotAllowed() *AddDefinitionMethodNotAllowed {
	return &AddDefinitionMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddDefinitionMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// AddDefinitionInternalServerErrorCode is the HTTP code returned for type AddDefinitionInternalServerError
const AddDefinitionInternalServerErrorCode int = 500

/*AddDefinitionInternalServerError Internal Error

swagger:response addDefinitionInternalServerError
*/
type AddDefinitionInternalServerError struct {
}

// NewAddDefinitionInternalServerError creates AddDefinitionInternalServerError with default headers values
func NewAddDefinitionInternalServerError() *AddDefinitionInternalServerError {
	return &AddDefinitionInternalServerError{}
}

// WriteResponse to the client
func (o *AddDefinitionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
