// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTypeOKCode is the HTTP code returned for type DeleteTypeOK
const DeleteTypeOKCode int = 200

/*DeleteTypeOK success

swagger:response deleteTypeOK
*/
type DeleteTypeOK struct {
}

// NewDeleteTypeOK creates DeleteTypeOK with default headers values
func NewDeleteTypeOK() *DeleteTypeOK {
	return &DeleteTypeOK{}
}

// WriteResponse to the client
func (o *DeleteTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteTypeBadRequestCode is the HTTP code returned for type DeleteTypeBadRequest
const DeleteTypeBadRequestCode int = 400

/*DeleteTypeBadRequest Invalid ID supplied

swagger:response deleteTypeBadRequest
*/
type DeleteTypeBadRequest struct {
}

// NewDeleteTypeBadRequest creates DeleteTypeBadRequest with default headers values
func NewDeleteTypeBadRequest() *DeleteTypeBadRequest {
	return &DeleteTypeBadRequest{}
}

// WriteResponse to the client
func (o *DeleteTypeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteTypeNotFoundCode is the HTTP code returned for type DeleteTypeNotFound
const DeleteTypeNotFoundCode int = 404

/*DeleteTypeNotFound Type not found

swagger:response deleteTypeNotFound
*/
type DeleteTypeNotFound struct {
}

// NewDeleteTypeNotFound creates DeleteTypeNotFound with default headers values
func NewDeleteTypeNotFound() *DeleteTypeNotFound {
	return &DeleteTypeNotFound{}
}

// WriteResponse to the client
func (o *DeleteTypeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteTypeInternalServerErrorCode is the HTTP code returned for type DeleteTypeInternalServerError
const DeleteTypeInternalServerErrorCode int = 500

/*DeleteTypeInternalServerError Internal Error

swagger:response deleteTypeInternalServerError
*/
type DeleteTypeInternalServerError struct {
}

// NewDeleteTypeInternalServerError creates DeleteTypeInternalServerError with default headers values
func NewDeleteTypeInternalServerError() *DeleteTypeInternalServerError {
	return &DeleteTypeInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteTypeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
