// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"models"
)

// GetConfigOKCode is the HTTP code returned for type GetConfigOK
const GetConfigOKCode int = 200

/*GetConfigOK Success

swagger:response getConfigOK
*/
type GetConfigOK struct {

	/*
	  In: Body
	*/
	Payload *models.Config `json:"body,omitempty"`
}

// NewGetConfigOK creates GetConfigOK with default headers values
func NewGetConfigOK() *GetConfigOK {
	return &GetConfigOK{}
}

// WithPayload adds the payload to the get config o k response
func (o *GetConfigOK) WithPayload(payload *models.Config) *GetConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config o k response
func (o *GetConfigOK) SetPayload(payload *models.Config) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigMethodNotAllowedCode is the HTTP code returned for type GetConfigMethodNotAllowed
const GetConfigMethodNotAllowedCode int = 405

/*GetConfigMethodNotAllowed Invalid input

swagger:response getConfigMethodNotAllowed
*/
type GetConfigMethodNotAllowed struct {
}

// NewGetConfigMethodNotAllowed creates GetConfigMethodNotAllowed with default headers values
func NewGetConfigMethodNotAllowed() *GetConfigMethodNotAllowed {
	return &GetConfigMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetConfigMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetConfigInternalServerErrorCode is the HTTP code returned for type GetConfigInternalServerError
const GetConfigInternalServerErrorCode int = 500

/*GetConfigInternalServerError Internal Error

swagger:response getConfigInternalServerError
*/
type GetConfigInternalServerError struct {
}

// NewGetConfigInternalServerError creates GetConfigInternalServerError with default headers values
func NewGetConfigInternalServerError() *GetConfigInternalServerError {
	return &GetConfigInternalServerError{}
}

// WriteResponse to the client
func (o *GetConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
