// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"models"
)

// GetOwnerTypesOKCode is the HTTP code returned for type GetOwnerTypesOK
const GetOwnerTypesOKCode int = 200

/*GetOwnerTypesOK Success

swagger:response getOwnerTypesOK
*/
type GetOwnerTypesOK struct {

	/*
	  In: Body
	*/
	Payload models.GetOwnerTypesOKBody `json:"body,omitempty"`
}

// NewGetOwnerTypesOK creates GetOwnerTypesOK with default headers values
func NewGetOwnerTypesOK() *GetOwnerTypesOK {
	return &GetOwnerTypesOK{}
}

// WithPayload adds the payload to the get owner types o k response
func (o *GetOwnerTypesOK) WithPayload(payload models.GetOwnerTypesOKBody) *GetOwnerTypesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get owner types o k response
func (o *GetOwnerTypesOK) SetPayload(payload models.GetOwnerTypesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOwnerTypesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetOwnerTypesOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetOwnerTypesMethodNotAllowedCode is the HTTP code returned for type GetOwnerTypesMethodNotAllowed
const GetOwnerTypesMethodNotAllowedCode int = 405

/*GetOwnerTypesMethodNotAllowed Invalid input

swagger:response getOwnerTypesMethodNotAllowed
*/
type GetOwnerTypesMethodNotAllowed struct {
}

// NewGetOwnerTypesMethodNotAllowed creates GetOwnerTypesMethodNotAllowed with default headers values
func NewGetOwnerTypesMethodNotAllowed() *GetOwnerTypesMethodNotAllowed {
	return &GetOwnerTypesMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetOwnerTypesMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetOwnerTypesInternalServerErrorCode is the HTTP code returned for type GetOwnerTypesInternalServerError
const GetOwnerTypesInternalServerErrorCode int = 500

/*GetOwnerTypesInternalServerError Internal Error

swagger:response getOwnerTypesInternalServerError
*/
type GetOwnerTypesInternalServerError struct {
}

// NewGetOwnerTypesInternalServerError creates GetOwnerTypesInternalServerError with default headers values
func NewGetOwnerTypesInternalServerError() *GetOwnerTypesInternalServerError {
	return &GetOwnerTypesInternalServerError{}
}

// WriteResponse to the client
func (o *GetOwnerTypesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
