// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"models"
)

// GetCategoriesOKCode is the HTTP code returned for type GetCategoriesOK
const GetCategoriesOKCode int = 200

/*GetCategoriesOK Success

swagger:response getCategoriesOK
*/
type GetCategoriesOK struct {

	/*
	  In: Body
	*/
	Payload models.GetCategoriesOKBody `json:"body,omitempty"`
}

// NewGetCategoriesOK creates GetCategoriesOK with default headers values
func NewGetCategoriesOK() *GetCategoriesOK {
	return &GetCategoriesOK{}
}

// WithPayload adds the payload to the get categories o k response
func (o *GetCategoriesOK) WithPayload(payload models.GetCategoriesOKBody) *GetCategoriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get categories o k response
func (o *GetCategoriesOK) SetPayload(payload models.GetCategoriesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetCategoriesOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetCategoriesMethodNotAllowedCode is the HTTP code returned for type GetCategoriesMethodNotAllowed
const GetCategoriesMethodNotAllowedCode int = 405

/*GetCategoriesMethodNotAllowed Invalid input

swagger:response getCategoriesMethodNotAllowed
*/
type GetCategoriesMethodNotAllowed struct {
}

// NewGetCategoriesMethodNotAllowed creates GetCategoriesMethodNotAllowed with default headers values
func NewGetCategoriesMethodNotAllowed() *GetCategoriesMethodNotAllowed {
	return &GetCategoriesMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetCategoriesMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetCategoriesInternalServerErrorCode is the HTTP code returned for type GetCategoriesInternalServerError
const GetCategoriesInternalServerErrorCode int = 500

/*GetCategoriesInternalServerError Internal Error

swagger:response getCategoriesInternalServerError
*/
type GetCategoriesInternalServerError struct {
}

// NewGetCategoriesInternalServerError creates GetCategoriesInternalServerError with default headers values
func NewGetCategoriesInternalServerError() *GetCategoriesInternalServerError {
	return &GetCategoriesInternalServerError{}
}

// WriteResponse to the client
func (o *GetCategoriesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
