// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"models"
)

// GetDefinitionsOKCode is the HTTP code returned for type GetDefinitionsOK
const GetDefinitionsOKCode int = 200

/*GetDefinitionsOK Success

swagger:response getDefinitionsOK
*/
type GetDefinitionsOK struct {

	/*
	  In: Body
	*/
	Payload models.PreferenceDefinitionArray `json:"body,omitempty"`
}

// NewGetDefinitionsOK creates GetDefinitionsOK with default headers values
func NewGetDefinitionsOK() *GetDefinitionsOK {
	return &GetDefinitionsOK{}
}

// WithPayload adds the payload to the get definitions o k response
func (o *GetDefinitionsOK) WithPayload(payload models.PreferenceDefinitionArray) *GetDefinitionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get definitions o k response
func (o *GetDefinitionsOK) SetPayload(payload models.PreferenceDefinitionArray) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDefinitionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.PreferenceDefinitionArray, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDefinitionsMethodNotAllowedCode is the HTTP code returned for type GetDefinitionsMethodNotAllowed
const GetDefinitionsMethodNotAllowedCode int = 405

/*GetDefinitionsMethodNotAllowed Invalid input

swagger:response getDefinitionsMethodNotAllowed
*/
type GetDefinitionsMethodNotAllowed struct {
}

// NewGetDefinitionsMethodNotAllowed creates GetDefinitionsMethodNotAllowed with default headers values
func NewGetDefinitionsMethodNotAllowed() *GetDefinitionsMethodNotAllowed {
	return &GetDefinitionsMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetDefinitionsMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// GetDefinitionsInternalServerErrorCode is the HTTP code returned for type GetDefinitionsInternalServerError
const GetDefinitionsInternalServerErrorCode int = 500

/*GetDefinitionsInternalServerError Internal Error

swagger:response getDefinitionsInternalServerError
*/
type GetDefinitionsInternalServerError struct {
}

// NewGetDefinitionsInternalServerError creates GetDefinitionsInternalServerError with default headers values
func NewGetDefinitionsInternalServerError() *GetDefinitionsInternalServerError {
	return &GetDefinitionsInternalServerError{}
}

// WriteResponse to the client
func (o *GetDefinitionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
