// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"models"
)

// GetDefinitionOKCode is the HTTP code returned for type GetDefinitionOK
const GetDefinitionOKCode int = 200

/*GetDefinitionOK successful operation

swagger:response getDefinitionOK
*/
type GetDefinitionOK struct {

	/*
	  In: Body
	*/
	Payload *models.PreferenceDefinition `json:"body,omitempty"`
}

// NewGetDefinitionOK creates GetDefinitionOK with default headers values
func NewGetDefinitionOK() *GetDefinitionOK {
	return &GetDefinitionOK{}
}

// WithPayload adds the payload to the get definition o k response
func (o *GetDefinitionOK) WithPayload(payload *models.PreferenceDefinition) *GetDefinitionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get definition o k response
func (o *GetDefinitionOK) SetPayload(payload *models.PreferenceDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDefinitionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDefinitionBadRequestCode is the HTTP code returned for type GetDefinitionBadRequest
const GetDefinitionBadRequestCode int = 400

/*GetDefinitionBadRequest Invalid ID supplied

swagger:response getDefinitionBadRequest
*/
type GetDefinitionBadRequest struct {
}

// NewGetDefinitionBadRequest creates GetDefinitionBadRequest with default headers values
func NewGetDefinitionBadRequest() *GetDefinitionBadRequest {
	return &GetDefinitionBadRequest{}
}

// WriteResponse to the client
func (o *GetDefinitionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetDefinitionNotFoundCode is the HTTP code returned for type GetDefinitionNotFound
const GetDefinitionNotFoundCode int = 404

/*GetDefinitionNotFound Pet not found

swagger:response getDefinitionNotFound
*/
type GetDefinitionNotFound struct {
}

// NewGetDefinitionNotFound creates GetDefinitionNotFound with default headers values
func NewGetDefinitionNotFound() *GetDefinitionNotFound {
	return &GetDefinitionNotFound{}
}

// WriteResponse to the client
func (o *GetDefinitionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetDefinitionInternalServerErrorCode is the HTTP code returned for type GetDefinitionInternalServerError
const GetDefinitionInternalServerErrorCode int = 500

/*GetDefinitionInternalServerError Internal Error

swagger:response getDefinitionInternalServerError
*/
type GetDefinitionInternalServerError struct {
}

// NewGetDefinitionInternalServerError creates GetDefinitionInternalServerError with default headers values
func NewGetDefinitionInternalServerError() *GetDefinitionInternalServerError {
	return &GetDefinitionInternalServerError{}
}

// WriteResponse to the client
func (o *GetDefinitionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
