// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"models"
)

// UpdateOwnerTypeOKCode is the HTTP code returned for type UpdateOwnerTypeOK
const UpdateOwnerTypeOKCode int = 200

/*UpdateOwnerTypeOK success

swagger:response updateOwnerTypeOK
*/
type UpdateOwnerTypeOK struct {

	/*
	  In: Body
	*/
	Payload *models.OwnerType `json:"body,omitempty"`
}

// NewUpdateOwnerTypeOK creates UpdateOwnerTypeOK with default headers values
func NewUpdateOwnerTypeOK() *UpdateOwnerTypeOK {
	return &UpdateOwnerTypeOK{}
}

// WithPayload adds the payload to the update owner type o k response
func (o *UpdateOwnerTypeOK) WithPayload(payload *models.OwnerType) *UpdateOwnerTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update owner type o k response
func (o *UpdateOwnerTypeOK) SetPayload(payload *models.OwnerType) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOwnerTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOwnerTypeBadRequestCode is the HTTP code returned for type UpdateOwnerTypeBadRequest
const UpdateOwnerTypeBadRequestCode int = 400

/*UpdateOwnerTypeBadRequest Invalid ID supplied

swagger:response updateOwnerTypeBadRequest
*/
type UpdateOwnerTypeBadRequest struct {
}

// NewUpdateOwnerTypeBadRequest creates UpdateOwnerTypeBadRequest with default headers values
func NewUpdateOwnerTypeBadRequest() *UpdateOwnerTypeBadRequest {
	return &UpdateOwnerTypeBadRequest{}
}

// WriteResponse to the client
func (o *UpdateOwnerTypeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateOwnerTypeNotFoundCode is the HTTP code returned for type UpdateOwnerTypeNotFound
const UpdateOwnerTypeNotFoundCode int = 404

/*UpdateOwnerTypeNotFound Definition not found

swagger:response updateOwnerTypeNotFound
*/
type UpdateOwnerTypeNotFound struct {
}

// NewUpdateOwnerTypeNotFound creates UpdateOwnerTypeNotFound with default headers values
func NewUpdateOwnerTypeNotFound() *UpdateOwnerTypeNotFound {
	return &UpdateOwnerTypeNotFound{}
}

// WriteResponse to the client
func (o *UpdateOwnerTypeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateOwnerTypeMethodNotAllowedCode is the HTTP code returned for type UpdateOwnerTypeMethodNotAllowed
const UpdateOwnerTypeMethodNotAllowedCode int = 405

/*UpdateOwnerTypeMethodNotAllowed Validation exception

swagger:response updateOwnerTypeMethodNotAllowed
*/
type UpdateOwnerTypeMethodNotAllowed struct {
}

// NewUpdateOwnerTypeMethodNotAllowed creates UpdateOwnerTypeMethodNotAllowed with default headers values
func NewUpdateOwnerTypeMethodNotAllowed() *UpdateOwnerTypeMethodNotAllowed {
	return &UpdateOwnerTypeMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateOwnerTypeMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// UpdateOwnerTypeInternalServerErrorCode is the HTTP code returned for type UpdateOwnerTypeInternalServerError
const UpdateOwnerTypeInternalServerErrorCode int = 500

/*UpdateOwnerTypeInternalServerError Internal Error

swagger:response updateOwnerTypeInternalServerError
*/
type UpdateOwnerTypeInternalServerError struct {
}

// NewUpdateOwnerTypeInternalServerError creates UpdateOwnerTypeInternalServerError with default headers values
func NewUpdateOwnerTypeInternalServerError() *UpdateOwnerTypeInternalServerError {
	return &UpdateOwnerTypeInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateOwnerTypeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
