// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateDefinitionHandlerFunc turns a function with the right signature into a update definition handler
type UpdateDefinitionHandlerFunc func(UpdateDefinitionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateDefinitionHandlerFunc) Handle(params UpdateDefinitionParams) middleware.Responder {
	return fn(params)
}

// UpdateDefinitionHandler interface for that can handle valid update definition params
type UpdateDefinitionHandler interface {
	Handle(UpdateDefinitionParams) middleware.Responder
}

// NewUpdateDefinition creates a new http.Handler for the update definition operation
func NewUpdateDefinition(ctx *middleware.Context, handler UpdateDefinitionHandler) *UpdateDefinition {
	return &UpdateDefinition{Context: ctx, Handler: handler}
}

/*UpdateDefinition swagger:route POST /definition/{id} Configuration updateDefinition

Update an existing Definition

*/
type UpdateDefinition struct {
	Context *middleware.Context
	Handler UpdateDefinitionHandler
}

func (o *UpdateDefinition) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateDefinitionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
