// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wtiger001/settingssvc/models"
)

// AddCategoryOKCode is the HTTP code returned for type AddCategoryOK
const AddCategoryOKCode int = 200

/*AddCategoryOK Success

swagger:response addCategoryOK
*/
type AddCategoryOK struct {

	/*
	  In: Body
	*/
	Payload *models.Category `json:"body,omitempty"`
}

// NewAddCategoryOK creates AddCategoryOK with default headers values
func NewAddCategoryOK() *AddCategoryOK {
	return &AddCategoryOK{}
}

// WithPayload adds the payload to the add category o k response
func (o *AddCategoryOK) WithPayload(payload *models.Category) *AddCategoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add category o k response
func (o *AddCategoryOK) SetPayload(payload *models.Category) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCategoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddCategoryMethodNotAllowedCode is the HTTP code returned for type AddCategoryMethodNotAllowed
const AddCategoryMethodNotAllowedCode int = 405

/*AddCategoryMethodNotAllowed Invalid input

swagger:response addCategoryMethodNotAllowed
*/
type AddCategoryMethodNotAllowed struct {
}

// NewAddCategoryMethodNotAllowed creates AddCategoryMethodNotAllowed with default headers values
func NewAddCategoryMethodNotAllowed() *AddCategoryMethodNotAllowed {
	return &AddCategoryMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddCategoryMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// AddCategoryInternalServerErrorCode is the HTTP code returned for type AddCategoryInternalServerError
const AddCategoryInternalServerErrorCode int = 500

/*AddCategoryInternalServerError Internal Error

swagger:response addCategoryInternalServerError
*/
type AddCategoryInternalServerError struct {
}

// NewAddCategoryInternalServerError creates AddCategoryInternalServerError with default headers values
func NewAddCategoryInternalServerError() *AddCategoryInternalServerError {
	return &AddCategoryInternalServerError{}
}

// WriteResponse to the client
func (o *AddCategoryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
