// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteTypeHandlerFunc turns a function with the right signature into a delete type handler
type DeleteTypeHandlerFunc func(DeleteTypeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTypeHandlerFunc) Handle(params DeleteTypeParams) middleware.Responder {
	return fn(params)
}

// DeleteTypeHandler interface for that can handle valid delete type params
type DeleteTypeHandler interface {
	Handle(DeleteTypeParams) middleware.Responder
}

// NewDeleteType creates a new http.Handler for the delete type operation
func NewDeleteType(ctx *middleware.Context, handler DeleteTypeHandler) *DeleteType {
	return &DeleteType{Context: ctx, Handler: handler}
}

/*DeleteType swagger:route DELETE /type/{id} Configuration deleteType

Deletes a type

*/
type DeleteType struct {
	Context *middleware.Context
	Handler DeleteTypeHandler
}

func (o *DeleteType) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTypeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
