// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteDefinitionHandlerFunc turns a function with the right signature into a delete definition handler
type DeleteDefinitionHandlerFunc func(DeleteDefinitionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDefinitionHandlerFunc) Handle(params DeleteDefinitionParams) middleware.Responder {
	return fn(params)
}

// DeleteDefinitionHandler interface for that can handle valid delete definition params
type DeleteDefinitionHandler interface {
	Handle(DeleteDefinitionParams) middleware.Responder
}

// NewDeleteDefinition creates a new http.Handler for the delete definition operation
func NewDeleteDefinition(ctx *middleware.Context, handler DeleteDefinitionHandler) *DeleteDefinition {
	return &DeleteDefinition{Context: ctx, Handler: handler}
}

/*DeleteDefinition swagger:route DELETE /definition/{id} Configuration deleteDefinition

Deletes a definition

*/
type DeleteDefinition struct {
	Context *middleware.Context
	Handler DeleteDefinitionHandler
}

func (o *DeleteDefinition) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDefinitionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
