// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteDefinitionOKCode is the HTTP code returned for type DeleteDefinitionOK
const DeleteDefinitionOKCode int = 200

/*DeleteDefinitionOK Success

swagger:response deleteDefinitionOK
*/
type DeleteDefinitionOK struct {
}

// NewDeleteDefinitionOK creates DeleteDefinitionOK with default headers values
func NewDeleteDefinitionOK() *DeleteDefinitionOK {
	return &DeleteDefinitionOK{}
}

// WriteResponse to the client
func (o *DeleteDefinitionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteDefinitionBadRequestCode is the HTTP code returned for type DeleteDefinitionBadRequest
const DeleteDefinitionBadRequestCode int = 400

/*DeleteDefinitionBadRequest Invalid ID supplied

swagger:response deleteDefinitionBadRequest
*/
type DeleteDefinitionBadRequest struct {
}

// NewDeleteDefinitionBadRequest creates DeleteDefinitionBadRequest with default headers values
func NewDeleteDefinitionBadRequest() *DeleteDefinitionBadRequest {
	return &DeleteDefinitionBadRequest{}
}

// WriteResponse to the client
func (o *DeleteDefinitionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteDefinitionNotFoundCode is the HTTP code returned for type DeleteDefinitionNotFound
const DeleteDefinitionNotFoundCode int = 404

/*DeleteDefinitionNotFound Definition not found

swagger:response deleteDefinitionNotFound
*/
type DeleteDefinitionNotFound struct {
}

// NewDeleteDefinitionNotFound creates DeleteDefinitionNotFound with default headers values
func NewDeleteDefinitionNotFound() *DeleteDefinitionNotFound {
	return &DeleteDefinitionNotFound{}
}

// WriteResponse to the client
func (o *DeleteDefinitionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteDefinitionInternalServerErrorCode is the HTTP code returned for type DeleteDefinitionInternalServerError
const DeleteDefinitionInternalServerErrorCode int = 500

/*DeleteDefinitionInternalServerError Internal Error

swagger:response deleteDefinitionInternalServerError
*/
type DeleteDefinitionInternalServerError struct {
}

// NewDeleteDefinitionInternalServerError creates DeleteDefinitionInternalServerError with default headers values
func NewDeleteDefinitionInternalServerError() *DeleteDefinitionInternalServerError {
	return &DeleteDefinitionInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteDefinitionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
