// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetOwnerTypesParams creates a new GetOwnerTypesParams object
// with the default values initialized.
func NewGetOwnerTypesParams() GetOwnerTypesParams {
	var ()
	return GetOwnerTypesParams{}
}

// GetOwnerTypesParams contains all the bound params for the get owner types operation
// typically these are obtained from a http.Request
//
// swagger:parameters getOwnerTypes
type GetOwnerTypesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetOwnerTypesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
