// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOwnerTypesHandlerFunc turns a function with the right signature into a get owner types handler
type GetOwnerTypesHandlerFunc func(GetOwnerTypesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOwnerTypesHandlerFunc) Handle(params GetOwnerTypesParams) middleware.Responder {
	return fn(params)
}

// GetOwnerTypesHandler interface for that can handle valid get owner types params
type GetOwnerTypesHandler interface {
	Handle(GetOwnerTypesParams) middleware.Responder
}

// NewGetOwnerTypes creates a new http.Handler for the get owner types operation
func NewGetOwnerTypes(ctx *middleware.Context, handler GetOwnerTypesHandler) *GetOwnerTypes {
	return &GetOwnerTypes{Context: ctx, Handler: handler}
}

/*GetOwnerTypes swagger:route GET /type Configuration getOwnerTypes

Get all owner types

*/
type GetOwnerTypes struct {
	Context *middleware.Context
	Handler GetOwnerTypesHandler
}

func (o *GetOwnerTypes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOwnerTypesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
