// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTypeHandlerFunc turns a function with the right signature into a get type handler
type GetTypeHandlerFunc func(GetTypeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTypeHandlerFunc) Handle(params GetTypeParams) middleware.Responder {
	return fn(params)
}

// GetTypeHandler interface for that can handle valid get type params
type GetTypeHandler interface {
	Handle(GetTypeParams) middleware.Responder
}

// NewGetType creates a new http.Handler for the get type operation
func NewGetType(ctx *middleware.Context, handler GetTypeHandler) *GetType {
	return &GetType{Context: ctx, Handler: handler}
}

/*GetType swagger:route GET /type/{id} Configuration getType

Find type by ID

Returns a single owner type

*/
type GetType struct {
	Context *middleware.Context
	Handler GetTypeHandler
}

func (o *GetType) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTypeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
