// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDefinitionsHandlerFunc turns a function with the right signature into a get definitions handler
type GetDefinitionsHandlerFunc func(GetDefinitionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDefinitionsHandlerFunc) Handle(params GetDefinitionsParams) middleware.Responder {
	return fn(params)
}

// GetDefinitionsHandler interface for that can handle valid get definitions params
type GetDefinitionsHandler interface {
	Handle(GetDefinitionsParams) middleware.Responder
}

// NewGetDefinitions creates a new http.Handler for the get definitions operation
func NewGetDefinitions(ctx *middleware.Context, handler GetDefinitionsHandler) *GetDefinitions {
	return &GetDefinitions{Context: ctx, Handler: handler}
}

/*GetDefinitions swagger:route GET /definition Configuration getDefinitions

Get all preference definitions

*/
type GetDefinitions struct {
	Context *middleware.Context
	Handler GetDefinitionsHandler
}

func (o *GetDefinitions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDefinitionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
