// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wtiger001/settingssvc/models"
)

// GetTypeOKCode is the HTTP code returned for type GetTypeOK
const GetTypeOKCode int = 200

/*GetTypeOK successful operation

swagger:response getTypeOK
*/
type GetTypeOK struct {

	/*
	  In: Body
	*/
	Payload *models.OwnerType `json:"body,omitempty"`
}

// NewGetTypeOK creates GetTypeOK with default headers values
func NewGetTypeOK() *GetTypeOK {
	return &GetTypeOK{}
}

// WithPayload adds the payload to the get type o k response
func (o *GetTypeOK) WithPayload(payload *models.OwnerType) *GetTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get type o k response
func (o *GetTypeOK) SetPayload(payload *models.OwnerType) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTypeBadRequestCode is the HTTP code returned for type GetTypeBadRequest
const GetTypeBadRequestCode int = 400

/*GetTypeBadRequest Invalid ID supplied

swagger:response getTypeBadRequest
*/
type GetTypeBadRequest struct {
}

// NewGetTypeBadRequest creates GetTypeBadRequest with default headers values
func NewGetTypeBadRequest() *GetTypeBadRequest {
	return &GetTypeBadRequest{}
}

// WriteResponse to the client
func (o *GetTypeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetTypeNotFoundCode is the HTTP code returned for type GetTypeNotFound
const GetTypeNotFoundCode int = 404

/*GetTypeNotFound Not found

swagger:response getTypeNotFound
*/
type GetTypeNotFound struct {
}

// NewGetTypeNotFound creates GetTypeNotFound with default headers values
func NewGetTypeNotFound() *GetTypeNotFound {
	return &GetTypeNotFound{}
}

// WriteResponse to the client
func (o *GetTypeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetTypeInternalServerErrorCode is the HTTP code returned for type GetTypeInternalServerError
const GetTypeInternalServerErrorCode int = 500

/*GetTypeInternalServerError Internal Error

swagger:response getTypeInternalServerError
*/
type GetTypeInternalServerError struct {
}

// NewGetTypeInternalServerError creates GetTypeInternalServerError with default headers values
func NewGetTypeInternalServerError() *GetTypeInternalServerError {
	return &GetTypeInternalServerError{}
}

// WriteResponse to the client
func (o *GetTypeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
