// Code generated by go-swagger; DO NOT EDIT.

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wtiger001/settingssvc/models"
)

// UpdateDefinitionOKCode is the HTTP code returned for type UpdateDefinitionOK
const UpdateDefinitionOKCode int = 200

/*UpdateDefinitionOK Success

swagger:response updateDefinitionOK
*/
type UpdateDefinitionOK struct {

	/*
	  In: Body
	*/
	Payload *models.PreferenceDefinition `json:"body,omitempty"`
}

// NewUpdateDefinitionOK creates UpdateDefinitionOK with default headers values
func NewUpdateDefinitionOK() *UpdateDefinitionOK {
	return &UpdateDefinitionOK{}
}

// WithPayload adds the payload to the update definition o k response
func (o *UpdateDefinitionOK) WithPayload(payload *models.PreferenceDefinition) *UpdateDefinitionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update definition o k response
func (o *UpdateDefinitionOK) SetPayload(payload *models.PreferenceDefinition) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDefinitionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateDefinitionBadRequestCode is the HTTP code returned for type UpdateDefinitionBadRequest
const UpdateDefinitionBadRequestCode int = 400

/*UpdateDefinitionBadRequest Invalid ID supplied

swagger:response updateDefinitionBadRequest
*/
type UpdateDefinitionBadRequest struct {
}

// NewUpdateDefinitionBadRequest creates UpdateDefinitionBadRequest with default headers values
func NewUpdateDefinitionBadRequest() *UpdateDefinitionBadRequest {
	return &UpdateDefinitionBadRequest{}
}

// WriteResponse to the client
func (o *UpdateDefinitionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateDefinitionNotFoundCode is the HTTP code returned for type UpdateDefinitionNotFound
const UpdateDefinitionNotFoundCode int = 404

/*UpdateDefinitionNotFound Definition not found

swagger:response updateDefinitionNotFound
*/
type UpdateDefinitionNotFound struct {
}

// NewUpdateDefinitionNotFound creates UpdateDefinitionNotFound with default headers values
func NewUpdateDefinitionNotFound() *UpdateDefinitionNotFound {
	return &UpdateDefinitionNotFound{}
}

// WriteResponse to the client
func (o *UpdateDefinitionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateDefinitionMethodNotAllowedCode is the HTTP code returned for type UpdateDefinitionMethodNotAllowed
const UpdateDefinitionMethodNotAllowedCode int = 405

/*UpdateDefinitionMethodNotAllowed Validation exception

swagger:response updateDefinitionMethodNotAllowed
*/
type UpdateDefinitionMethodNotAllowed struct {
}

// NewUpdateDefinitionMethodNotAllowed creates UpdateDefinitionMethodNotAllowed with default headers values
func NewUpdateDefinitionMethodNotAllowed() *UpdateDefinitionMethodNotAllowed {
	return &UpdateDefinitionMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateDefinitionMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// UpdateDefinitionInternalServerErrorCode is the HTTP code returned for type UpdateDefinitionInternalServerError
const UpdateDefinitionInternalServerErrorCode int = 500

/*UpdateDefinitionInternalServerError Internal Error

swagger:response updateDefinitionInternalServerError
*/
type UpdateDefinitionInternalServerError struct {
}

// NewUpdateDefinitionInternalServerError creates UpdateDefinitionInternalServerError with default headers values
func NewUpdateDefinitionInternalServerError() *UpdateDefinitionInternalServerError {
	return &UpdateDefinitionInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateDefinitionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
