// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteProfileOKCode is the HTTP code returned for type DeleteProfileOK
const DeleteProfileOKCode int = 200

/*DeleteProfileOK success

swagger:response deleteProfileOK
*/
type DeleteProfileOK struct {
}

// NewDeleteProfileOK creates DeleteProfileOK with default headers values
func NewDeleteProfileOK() *DeleteProfileOK {
	return &DeleteProfileOK{}
}

// WriteResponse to the client
func (o *DeleteProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteProfileBadRequestCode is the HTTP code returned for type DeleteProfileBadRequest
const DeleteProfileBadRequestCode int = 400

/*DeleteProfileBadRequest Invalid ID supplied

swagger:response deleteProfileBadRequest
*/
type DeleteProfileBadRequest struct {
}

// NewDeleteProfileBadRequest creates DeleteProfileBadRequest with default headers values
func NewDeleteProfileBadRequest() *DeleteProfileBadRequest {
	return &DeleteProfileBadRequest{}
}

// WriteResponse to the client
func (o *DeleteProfileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteProfileNotFoundCode is the HTTP code returned for type DeleteProfileNotFound
const DeleteProfileNotFoundCode int = 404

/*DeleteProfileNotFound Type not found

swagger:response deleteProfileNotFound
*/
type DeleteProfileNotFound struct {
}

// NewDeleteProfileNotFound creates DeleteProfileNotFound with default headers values
func NewDeleteProfileNotFound() *DeleteProfileNotFound {
	return &DeleteProfileNotFound{}
}

// WriteResponse to the client
func (o *DeleteProfileNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteProfileInternalServerErrorCode is the HTTP code returned for type DeleteProfileInternalServerError
const DeleteProfileInternalServerErrorCode int = 500

/*DeleteProfileInternalServerError Internal Error

swagger:response deleteProfileInternalServerError
*/
type DeleteProfileInternalServerError struct {
}

// NewDeleteProfileInternalServerError creates DeleteProfileInternalServerError with default headers values
func NewDeleteProfileInternalServerError() *DeleteProfileInternalServerError {
	return &DeleteProfileInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteProfileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
