// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteOwnerOKCode is the HTTP code returned for type DeleteOwnerOK
const DeleteOwnerOKCode int = 200

/*DeleteOwnerOK success

swagger:response deleteOwnerOK
*/
type DeleteOwnerOK struct {
}

// NewDeleteOwnerOK creates DeleteOwnerOK with default headers values
func NewDeleteOwnerOK() *DeleteOwnerOK {
	return &DeleteOwnerOK{}
}

// WriteResponse to the client
func (o *DeleteOwnerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteOwnerBadRequestCode is the HTTP code returned for type DeleteOwnerBadRequest
const DeleteOwnerBadRequestCode int = 400

/*DeleteOwnerBadRequest Invalid ID supplied

swagger:response deleteOwnerBadRequest
*/
type DeleteOwnerBadRequest struct {
}

// NewDeleteOwnerBadRequest creates DeleteOwnerBadRequest with default headers values
func NewDeleteOwnerBadRequest() *DeleteOwnerBadRequest {
	return &DeleteOwnerBadRequest{}
}

// WriteResponse to the client
func (o *DeleteOwnerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteOwnerNotFoundCode is the HTTP code returned for type DeleteOwnerNotFound
const DeleteOwnerNotFoundCode int = 404

/*DeleteOwnerNotFound Type not found

swagger:response deleteOwnerNotFound
*/
type DeleteOwnerNotFound struct {
}

// NewDeleteOwnerNotFound creates DeleteOwnerNotFound with default headers values
func NewDeleteOwnerNotFound() *DeleteOwnerNotFound {
	return &DeleteOwnerNotFound{}
}

// WriteResponse to the client
func (o *DeleteOwnerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteOwnerInternalServerErrorCode is the HTTP code returned for type DeleteOwnerInternalServerError
const DeleteOwnerInternalServerErrorCode int = 500

/*DeleteOwnerInternalServerError Internal Error

swagger:response deleteOwnerInternalServerError
*/
type DeleteOwnerInternalServerError struct {
}

// NewDeleteOwnerInternalServerError creates DeleteOwnerInternalServerError with default headers values
func NewDeleteOwnerInternalServerError() *DeleteOwnerInternalServerError {
	return &DeleteOwnerInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteOwnerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
