// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wtiger001/settingssvc/models"
)

// GetMyActiveProfileOKCode is the HTTP code returned for type GetMyActiveProfileOK
const GetMyActiveProfileOKCode int = 200

/*GetMyActiveProfileOK successful operation

swagger:response getMyActiveProfileOK
*/
type GetMyActiveProfileOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewGetMyActiveProfileOK creates GetMyActiveProfileOK with default headers values
func NewGetMyActiveProfileOK() *GetMyActiveProfileOK {
	return &GetMyActiveProfileOK{}
}

// WithPayload adds the payload to the get my active profile o k response
func (o *GetMyActiveProfileOK) WithPayload(payload *models.Profile) *GetMyActiveProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get my active profile o k response
func (o *GetMyActiveProfileOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMyActiveProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMyActiveProfileBadRequestCode is the HTTP code returned for type GetMyActiveProfileBadRequest
const GetMyActiveProfileBadRequestCode int = 400

/*GetMyActiveProfileBadRequest Invalid ID supplied

swagger:response getMyActiveProfileBadRequest
*/
type GetMyActiveProfileBadRequest struct {
}

// NewGetMyActiveProfileBadRequest creates GetMyActiveProfileBadRequest with default headers values
func NewGetMyActiveProfileBadRequest() *GetMyActiveProfileBadRequest {
	return &GetMyActiveProfileBadRequest{}
}

// WriteResponse to the client
func (o *GetMyActiveProfileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetMyActiveProfileNotFoundCode is the HTTP code returned for type GetMyActiveProfileNotFound
const GetMyActiveProfileNotFoundCode int = 404

/*GetMyActiveProfileNotFound Not found

swagger:response getMyActiveProfileNotFound
*/
type GetMyActiveProfileNotFound struct {
}

// NewGetMyActiveProfileNotFound creates GetMyActiveProfileNotFound with default headers values
func NewGetMyActiveProfileNotFound() *GetMyActiveProfileNotFound {
	return &GetMyActiveProfileNotFound{}
}

// WriteResponse to the client
func (o *GetMyActiveProfileNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetMyActiveProfileInternalServerErrorCode is the HTTP code returned for type GetMyActiveProfileInternalServerError
const GetMyActiveProfileInternalServerErrorCode int = 500

/*GetMyActiveProfileInternalServerError Internal Error

swagger:response getMyActiveProfileInternalServerError
*/
type GetMyActiveProfileInternalServerError struct {
}

// NewGetMyActiveProfileInternalServerError creates GetMyActiveProfileInternalServerError with default headers values
func NewGetMyActiveProfileInternalServerError() *GetMyActiveProfileInternalServerError {
	return &GetMyActiveProfileInternalServerError{}
}

// WriteResponse to the client
func (o *GetMyActiveProfileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
