// Code generated by go-swagger; DO NOT EDIT.

package preferences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateOwnerHandlerFunc turns a function with the right signature into a update owner handler
type UpdateOwnerHandlerFunc func(UpdateOwnerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateOwnerHandlerFunc) Handle(params UpdateOwnerParams) middleware.Responder {
	return fn(params)
}

// UpdateOwnerHandler interface for that can handle valid update owner params
type UpdateOwnerHandler interface {
	Handle(UpdateOwnerParams) middleware.Responder
}

// NewUpdateOwner creates a new http.Handler for the update owner operation
func NewUpdateOwner(ctx *middleware.Context, handler UpdateOwnerHandler) *UpdateOwner {
	return &UpdateOwner{Context: ctx, Handler: handler}
}

/*UpdateOwner swagger:route POST /owner/{id} Preferences updateOwner

Update an existing owner

*/
type UpdateOwner struct {
	Context *middleware.Context
	Handler UpdateOwnerHandler
}

func (o *UpdateOwner) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateOwnerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
