// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OwnerType owner type
// swagger:model OwnerType
type OwnerType struct {

	// definitions
	Definitions []string `json:"definitions"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this owner type
func (m *OwnerType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefinitions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OwnerType) validateDefinitions(formats strfmt.Registry) error {

	if swag.IsZero(m.Definitions) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OwnerType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OwnerType) UnmarshalBinary(b []byte) error {
	var res OwnerType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
