// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PreferenceDefinition preference definition
// swagger:model PreferenceDefinition
type PreferenceDefinition struct {

	// category
	Category string `json:"category,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// Layout Instructions
	Layout interface{} `json:"layout,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// JSON Schema
	Schema interface{} `json:"schema,omitempty"`

	//HACK
	JsonData map[string]*json.RawMessage `json:"-"`
}

// Validate validates this preference definition
func (m *PreferenceDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PreferenceDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PreferenceDefinition) UnmarshalBinary(b []byte) error {
	var res PreferenceDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
