// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Preferences Store
Definition for the Preferences Server


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
